name: Complie

on: 
  workflow_dispatch:

jobs: 
  Complie:
   name: Complie the C file
   runs-on: ubuntu-latest
   
   steps: 
     - name: Checkout
       uses: actions/checkout@v2
       
     - name: Complie
       run: |
         mkdir artifact && cd artifact 
         g++ ../1.cpp -o 1.out
         
     - name: Upload artifact
       uses: actions/upload-artifact@v2
       with:
         name: Exec File
         path: artifact
